// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, kReleaseMode, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  /// リリースビルドは本番（ukalab-prod）、それ以外（debug/profile）は開発（ukalab-dev）。
  /// どちらも うかラボ共通プロジェクト。データは users/{uid}/exams/bike_license/ 配下。
  static FirebaseOptions get android => kReleaseMode ? _androidProd : _androidDev;

  static const FirebaseOptions _androidProd = FirebaseOptions(
    apiKey: 'AIzaSyDZdjJ53kTfALpV_ti_ipLpxMeNVhLXOAE',
    appId: '1:264757683394:android:5c55a24c475646a79a475b',
    messagingSenderId: '264757683394',
    projectId: 'ukalab-prod',
    storageBucket: 'ukalab-prod.firebasestorage.app',
  );

  static const FirebaseOptions _androidDev = FirebaseOptions(
    apiKey: 'AIzaSyCtYZQVS6ZElOuJwXnYZERNctGeB8G9wuY',
    appId: '1:765180094909:android:a7cd1214cb0165390e8ad4',
    messagingSenderId: '765180094909',
    projectId: 'ukalab-dev',
    storageBucket: 'ukalab-dev.firebasestorage.app',
  );
}
