// This file is generated by the Firebase CLI.
// DO NOT modify this file manually.
// Generated firebase options for cross-platform access

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    // Placeholder configuration - update with actual Firebase project details
    return FirebaseOptions(
      apiKey: 'AIzaSyDummy_Firebase_API_Key_For_Development',
      appId: '1:123456789:android:abc123def456ghi',
      messagingSenderId: '123456789',
      projectId: 'bike-license-project',
      storageBucket: 'bike-license-project.appspot.com',
      iosBundleId: 'com.example.bike',
    );
  }

  // Platform-specific options can be added here if needed
  static FirebaseOptions get android {
    return FirebaseOptions(
      apiKey: 'AIzaSyDummy_Firebase_API_Key_For_Development',
      appId: '1:123456789:android:abc123def456ghi',
      messagingSenderId: '123456789',
      projectId: 'bike-license-project',
      storageBucket: 'bike-license-project.appspot.com',
    );
  }

  static FirebaseOptions get ios {
    return FirebaseOptions(
      apiKey: 'AIzaSyDummy_Firebase_API_Key_For_Development',
      appId: '1:123456789:ios:abc123def456ghi',
      messagingSenderId: '123456789',
      projectId: 'bike-license-project',
      storageBucket: 'bike-license-project.appspot.com',
      iosBundleId: 'com.example.bike',
    );
  }
}
